### PR TITLE
fixes  "//@todo refactor this compare logic, do routeAcceptedParameters ...

### PR DESCRIPTION
**Pull request by AleX-YaR**
fixes  "//@todo refactor this compare logic, do routeAcceptedParameters and routeRequiredParameters to same format" in MenuFactory.php line 146

faced this problem when was doing a multilanguage site

### CODE REVIEW

**Comment by paramonov** [comment]
Hello. Do you think **merge** this request? my submenu items is not displayed.

**Comment by HadesArchitect** [comment]
Hello, @paramonov. I'm sorry, but as far as i know, @zerkalica dropped the project since he moved to another programming language.

@zerkalica, i still use the bundle and could maintain it if you'd like to.

**Comment by paramonov** [comment]
Very-very sorry

**Comment by paramonov** [comment]
@zerkalica, I thank you very much))

**Pull request merged**
